name: PHP7.4 Tests

on:
  pull_request: null

env:
  # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
  COMPOSER_ROOT_VERSION: "dev-main"

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    name: PHP 7.4 tests

    steps:
      -   uses: actions/checkout@v2

      # see https://github.com/shivammathur/setup-php
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: 7.4
            coverage: none

      # composer install cache - https://github.com/ramsey/composer-install
      -   uses: "ramsey/composer-install@v1"

      -   run: composer require symfony/symfony:5.* --no-update --dev
      -   run: composer update --prefer-dist --no-interaction --dev
      -   run: bin/coke
      -   run: bin/atoum
