name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        php-version:
          - 7.2
          - 7.3
          - 7.4
        symfony-version:
          - 4.4.0
          - ^5.0
        experimental: [false]
        include:
          - php-version: 7.1
            symfony-version: 4.4.0
            experimental: false
          - php-version: 8.0
            symfony-version: ^5.0
            experimental: true

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install symfony version from matrix
        env:
          SYMFONY_VERSION: ${{ matrix.symfony-version }}
        run: composer require symfony/symfony:$SYMFONY_VERSION --no-update --dev
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --dev
      - name: Code style check
        run: bin/coke
      - name: Unit tests
        run: bin/atoum
