name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 7.2
          - 7.3
          - 7.4
          - 8.0
          - 8.1
        symfony-version:
          - 4.4.*
          - 5.3.*
          - 5.4.*
        include:
          - php-version: 7.1
            symfony-version: 4.4.*
          - php-version: 8.1
            symfony-version: 6.0.*

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install symfony version from matrix
        env:
          SYMFONY_VERSION: ${{ matrix.symfony-version }}
        run: composer require symfony/symfony:$SYMFONY_VERSION --no-update
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction
      - name: Code style check
        run: bin/php-cs-fixer fix --dry-run --using-cache=no --verbose
      - name: Unit tests
        run: bin/atoum
